Repository Chloekkk/minishell, pull requests merged in 2022-06, with the labels that each got.

#3 Hotfix/pr
  .github/PULL_REQUEST_TEMPLATE.md
Labels: setting

#2 Feature/parse
  Makefile
  include/ast.h
  include/minishell.h
  include/token.h
  libft/libft.h
  src/main.c
  src/parser/lexical_analyzer.c
  src/parser/syntax_analyzer.c
  src/parser/syntax_command.c
  src/parser/syntax_io_redirect.c
  src/parser/syntax_pipe_line.c
  src/parser/syntax_redirects.c
  src/parser/syntax_simple_command.c
  src/parser/token.c
  src/utils/ft_isspace.c
Labels: enhancement, feature

#1 Feature/builtin
  Makefile
  include/minishell.h
  libft/ft_strncmp.c
  src/builtin/ft_cd.c
  src/builtin/ft_echo.c
  src/builtin/ft_env.c
  src/builtin/ft_exit.c
  src/builtin/ft_export.c
  src/builtin/ft_pwd.c
  src/builtin/ft_unset.c
  src/env/env_list.c
  src/env/env_utils.c
  src/error/throw_error.c
  src/fork/processor.c
  src/main.c
  src/utils/free.c
Labels: enhancement, feature

#5 Hofix/variable_error
  include/minishell.h
  src/builtin/ft_env.c
  src/builtin/ft_export.c
  src/builtin/ft_unset.c
  src/env/env_list.c
  src/env/env_utils.c
  src/main.c
  src/utils/free.c
Labels: bug

#4 Feat/norminette_ci
  .github/workflows/norminette.yml
  include/minishell.h
  libft/ft_strjoin.c
  src/fork/processor.c
  src/main.c
  src/parser/lexical_analyzer.c
  src/parser/syntax_command.c
  src/parser/token.c
Labels: enhancement

#7 Feature/test builtin
  include/minishell.h
  include/test.h
  src/__test__/test_token.c
  src/main.c
  src/parser/syntax_analyzer.c
Labels: enhancement

#8 Feature/test ast
  Makefile
  include/ast.h
  include/minishell.h
  include/test.h
  src/__test__/test_ast.c
  src/main.c
  src/parser/syntax_analyzer.c
  src/parser/syntax_command.c
  src/parser/syntax_io_redirect.c
  src/parser/syntax_pipe_line.c
  src/parser/syntax_redirects.c
  src/parser/syntax_simple_command.c
Labels: enhancement, feature

#10 feat: Complete signal and history
  Makefile
  include/minishell.h
  src/exec/ft_execve.c
  src/main.c
  src/signal/ft_eof.c
  src/signal/ft_signal.c
Labels: feature

#13 Refactor/header
  Makefile
  include/builtin.h
  include/minishell.h
  include/parser.h
  src/__test__/test_token.c
  src/builtin/is_builtin.c
  src/exec/execute_builtin.c
  src/main.c
Labels: enhancement, setting

#14 Refactor/Rename execute_builtin.c to exec_builtin.c
  Makefile
  include/minishell.h
  src/__test__/test_token.c
  src/exec/exec_builtin.c
Labels: enhancement

#15 Hotfix/refactoring
  Makefile
  include/minishell.h
  src/builtin/ft_export.c
  src/builtin/ft_unset.c
  src/env/env_utils.c
  src/exec/exec_general.c
  src/main.c
  src/signal/check_signal.c
  src/utils/free.c
  src/utils/ft_exit_eof.c
Labels: enhancement

#19 Fix/Complete echo option exception like " -n -nn -nn"
  src/builtin/ft_echo.c
Labels: refactor

#22 Hotfix/signal exception
  include/minishell.h
  src/builtin/ft_exit.c
  src/exec/exec_general.c
  src/exec/exec_single_command.c
  src/main.c
  src/signal/check_signal.c
  src/subshell/create_subshell.c
Labels: bug

#29 style: Update prompt style
  include/minishell.h
Labels: feature

#30 Style/prompt-style
  include/minishell.h
Labels: bug

#35 Feature/splash_img
  include/minishell.h
  src/main.c
Labels: feature, refactor

#36 Style/makefile
  Makefile
  libft/Makefile
Labels: feature

#37 Refactor/exit code
  include/error.h
  src/exec/exec_general.c
  src/main.c
  src/redirect/redirect_heredoc.c
Labels: refactor

#38 Refactor/heredoc
  Makefile
  include/minishell.h
  include/signal.h
  src/redirect/redirect_heredoc.c
  src/signal/handle_signal_heredoc.c
Labels: refactor

#40 Hofix/quote and null error
  src/exec/exec_subshell.c
  src/parser/lexical_analyzer.c
  src/parser/syntax_analyzer.c
  src/parser/token.c
Labels: bug

#42 Fix/free_io_redirect unlink heredoc_path
  src/parser/free_io_redirect.c
Labels: bug

#43 fix: Fix leaks and segmentation fault
  src/env/remove_env.c
  src/parser/free_ast.c
  src/parser/free_simple_command.c
  src/parser/syntax_pipe_line.c
Labels: bug
