Repository Chloekkk/minishell, pull requests merged in 2022-07, with the labels that each got.

#46 [Fix] Multi heredoc redirect_op segfault error
  include/exec.h
  src/exec/exec_command_line.c
  src/exec/exec_heredoc.c
  src/main.c
  src/parser/get_combined_word.c
  src/parser/syntax_io_redirect.c
Labels: bug

#49 [Fix] pipe_line pipe command error
  src/parser/syntax_analyzer.c
  src/parser/syntax_pipe_line.c
Labels: bug

#50 Hotfix/builtin
  Makefile
  include/error.h
  include/utils.h
  src/builtin/ft_cd.c
  src/builtin/ft_exit.c
  src/exec/exec_general.c
  src/main.c
  src/utils/bs_find_path.c
Labels: bug, enhancement, feature

#51 Hotfix/builtin
  src/builtin/ft_exit.c
  src/error/throw_error_syntax.c
  src/error/throw_error_usage.c
  src/exec/exec_general.c
Labels: bug, enhancement

#52 [Hotfix] exit pipe err
  Makefile
  include/builtin.h
  include/redirect.h
  src/builtin/ft_exit.c
  src/exec/exec_simple_command.c
  src/exec/exec_single_command.c
  src/redirect/redirect_out_trash.c
Labels: bug

#53 [Fix] single_command redirects error
  src/exec/exec_single_command.c
Labels: bug

#54 fix: Fix env identifier
  src/env/valid_env_name.c
Labels: bug

#55 [Fix] syntax_redirect parsing error
  src/exec/exec_single_command.c
  src/parser/syntax_redirects.c
Labels: bug

#56 [Feature] Refactor Dockerfile && entrypoint.sh
  Dockerfile
  entrypoint.sh
Labels: enhancement, feature
